% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}
\usepackage{xcolor}
\usepackage[margin=2.54cm]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
  \setmainfont[]{Calibri}
  \setmonofont[Color=0070C0]{Consolas}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother

\ifLuaTeX
  \usepackage{luacolor}
  \usepackage[soul]{lua-ul}
\else
  \usepackage{soul}
\fi




\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{parskip}
\setlength{\parskip}{8pt}
\setlength{\parindent}{0pt}
\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={How did Ivory Coast win AFCON 2023 despite sacking their manager during the Tournament, and was it deserved?},
  pdfauthor={Arjan Nahal (201570800)},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{How did Ivory Coast win AFCON 2023 despite sacking their manager
during the Tournament, and was it deserved?}
\author{Arjan Nahal (201570800)}
\date{2026-05-15}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{3}
\tableofcontents
}
\listoffigures
\listoftables

\setstretch{1.15}
\section{My Resources}\label{my-resources}

\textbf{Live dashboard:}
\url{https://nahal12345.github.io/Sports-Data-and-Analytics-Assignment-/}

\textbf{Repository:}
\url{https://github.com/Nahal12345/Sports-Data-and-Analytics-Assignment-}

\newpage{}

\section{\texorpdfstring{\ul{Introduction}}{Introduction}}\label{introduction}

AFCON 2023 was hosted in Côte d'Ivoire (Ivory Coast), and it saw the
hosts lift the title. This victory was remarkable not just because it
was a home tournament, but the team were on the brink of elimination
during the group stage. After their win in the first game, Ivory Coast
followed that by losing two consecutive games to Nigeria and Equatorial
Guinea which saw them finish in 3rd place, narrowly qualifying due to
them being the 4th best 3rd place finishers. Due to this failure in the
group stage, the Ivorian Football Federation took the decision to sack
the head coach Jean-Louis Gasset and replace him with Emerese Faé, who
was the Ivory Coast under 23 coach.

Following this there was an unexpected revival, with Ivory Coast which
led to AFCON victory. Faé's side beat Senegal in the Round of 16, Mali
in the Quarter Final, Democratic Republic of Congo in the Semi Final,
and then defeated Nigeria in the final, which was one of the team's that
they had previously lost to in the group stage. They didn't only just
beat them, they beat them convincingly as they dominated the final. The
transformation between the two managers was visible, but the question
that this report seeks to answer is whether the data supports the
outcome: How did Ivory Coast win AFCON 2023 despite sacking their
manager during the Tournament, and was it deserved?

The question is interesting because football tournaments can be won due
to pure luck and individual brilliance whilst also posting poor
underlying numbers. On the contrast, a dominant team can lose to a
single moment . Expected Goals (xG), defensive action metrics, attacking
metrics and shot quality data offers a way to cut through the narrative
and allows us to analyse what exactly is happening with the players on
the pitch.

The dashboard and the accompanying analysis is structured around the
comparison between the group stage performance under Jean-Louis Gasset
and the Knockout Stage performance under Emerese Faé, which individual
players drove the improvement, and underlying data suggesting whether
the title was deserved. The data that has been used throughout this
report was sourced from StatsBomb's open data repository, which has
provided event-level data for the AFCON data. The dashboard is hosted
publicly on GitHub Pages and built using R, ggplot2 and Plotly, with the
full code available in the repository that has been linked.

\section{\texorpdfstring{\ul{Data Collection and
Preparation}}{Data Collection and Preparation}}\label{data-collection-and-preparation}

\subsection{\texorpdfstring{\ul{Data
Source}}{Data Source}}\label{data-source}

All the data that has been used in the analysis was obtained from
StatBomb's open data repository, which was computed into R via the
statsbombr package (STATSBOMB REFERENCE). This open data provided event
level match data for AFCON, which allowed for extensive game by game
analysis to be conducted. This was downloaded by:
devtools::install.github(``statsbomb/StatsBombR'').

The StatsBomb event data model captures every on the ball action in a
match as its own event, each with a timestamp, location (expressed as an
x,y coordinate on a 120 x 80 pitch), the player and the possession team
involved, and many more action specific events. The three primary
functions that were used to collect the data were
``\textbf{FreeCompetitions()``,''FreeMatches()'' and
``get.matchFree()''. FreeCompetitions()} was used to retrieve the full
list of available competitions and identified AFCON2023. To filter for
this, the competition id was filtered using 1267. This allowed for the
match data to be downloaded, which is where \textbf{FreeMatches()} was
used. In order to pull event level data from the matches,
\textbf{get.matchFree()} was used to return a database of every recorded
event, such as shots, passes, dribbles and duels etc.

\subsection{\texorpdfstring{\ul{Dataset structure and
coverage}}{Dataset structure and coverage}}\label{dataset-structure-and-coverage}

The final merged dataset consisted of all 52 AFCON 2023 matches. The
event level data frame consisted of 162,910 rows across all matches,
with each row representing a single recorded event. The key variables
used in this research were:

\begin{longtable}[]{@{}lll@{}}
\toprule\noalign{}
Variable & Type & Description \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
match\_id & Integer & Unique match identifier \\
competition\_stage.name & Character & Round of competition \\
team.name & Character & Team Name \\
type.name & Character & Event type \\
shot.statsbomb\_xg & Double & Expected goals value \\
shot.outcome\_name & Character & Shot result \\
player.name & Character & Full player name \\
location & List & x,y coordinates on the pitch \\
minute/second & Integer & Event timestamp \\
possession\_team.name & Character & Team in possession \\
duel.type.name & Character & Type of duel occuring \\
pass.goal\_assist & Logial & Whether the pass led to a goal \\
\end{longtable}

For Ivory Coast specifically, the \textbf{ivorycoast\_matches} subset
identified the seven matches that they played in. The events from these
matches were filtered from \textbf{all\_events} using the match\_id to
analyse specific matches. This allowed for specific event data to be
pulled from their matches, and using \textbf{possession\_team.name ==
``Côte d'Ivoire''} allowed for a more focused view on the team.

One important structural decision that was required to be made was the
exclusion of \textbf{``period ==5'',} which corresponds to a penalty
shootout in Statsbomb databases. This was done as the penalty shootout
goals, shots and xG were being included into the overall shot and goal
analysis. Including these events would have altered the results, as
penalty shootouts occur outside of normal time, therefore they do not
represent in game performance in the same way that the regular event
data does. Penalties carry a very high xG value, which would mean that
when analysing the cumulative xG for Ivory Coast throughout the
tournament, the penalty shootout vs Senegal would have interfered with
the data collection.

\subsection{\texorpdfstring{\ul{Cleaning and
Preparation}}{Cleaning and Preparation}}\label{cleaning-and-preparation}

Before any of the metrics were computed, data cleaning and preparation
steps were applied to ensure that the raw data was suitable for the
analysis that was being prepared.

Spatial coordinates in the StatsBomb dataset are stored a list columns
rather than standard numeric vectors, with each of the event data's
location being represented by an x and y value. For the simple
extractions, ``sapply'' was used to pull the first and second elements
of each location list. For the larger extractions where columns could
contain empty entries, ``map\_dbl'' was used to to substitute NA where
the coordinates were missing. This ensured that any missing coordinate
values did not cause any incorrect results within the analysis.

Shot outcomes were recoded from StatsBombs's categories into four
different outcomes to be used across the shot maps. To keep the shot
maps clean and readable, outcomes such as `Saved to Post' were
deliberately combined into `Saved' rather than keeping it as it's own
outcome. The four outcomes used were `Saved', `Blocked', `Off Target'
and `Goal'. Shots were also filtered to exclude `period 5' , which
represents the penalty shootout. Including shots from penalty shootouts
would have distorted the shot location data, as it would have inflated
shot totals without affecting in game events.

A binary manager variable was created directly from
``competition\_stage.name'', which assigned the Group Stage matches to
Jean-Louis Gasset and the Knockout Stage to Emerse Faé. This allowed for
a direct comparison between the managers across each metric in the
dashboard without having to go game by game. It meant that every match
was assigned to the correct manager in the same way across every single
section of the analysis.

\subsection{\texorpdfstring{\ul{Limitations of the
Data}}{Limitations of the Data}}\label{limitations-of-the-data}

There are certain limitations of the data set which affected the
research. Firstly, the Statsbomb open data does not include tracking
data (player positions in between the events), which limits the amount
of off the ball metrics. This includes the pressing intensity and the
overall defensive structure. Linking to this, the xG model used will not
take underlying metrics such as pressure on the attacker, or how close
the defender is, meaning the calculated xG values may not fully reflect
the true quaility and difficulty of the chance. Some of the results may
be overvalued and some may be undervalued compared to the actual context
of the shot.

The data does not take into account game state, meaning that events
occurring when a team is winning, drawing or losing are all treated
equally. This is a relevant limitation to the data because different
circumstances in games cause different outcomes. For example, teams who
are losing will take a lot more risks, which could lead to them taking
more shots out of desperation, take more risks in passing and press
higher up the pitch, which would inflate certain metrics. On the other
hand, teams who are winning may not sit a lot deeper and concede more
possession, therefore deflating their attacking metrics but inflate
their defensive stats as they are inviting on pressure. For example, as
Ivory Coast lost the first two games, it is possible that some of the
metrics were impacted by the fact that they were chasing the game, which
would have inflated their stats. Whereas with Faé, in the game against
Mali they had a player who was sent off, meaning they were under a lot
of pressure from the opposing team. Therefore, the defensive stats would
be increasingly inflated because of this.

\section{\texorpdfstring{\ul{Methodology}}{Methodology}}\label{methodology}

\subsection{\texorpdfstring{\ul{Going from raw data to
dashboard}}{Going from raw data to dashboard}}\label{going-from-raw-data-to-dashboard}

Once the binary variables were created, it allowed for all the metrics,
visualisations and tables to be split between each managerial era
consistently. All the data was seperated into their own figures, graphs
and tables and then saved individually as RDS files using ``saveRDS()''.
This meant that the dashboard was able to load the data using
``readRDS()''. This meant that instead of the dashboard having to
process the raw data every time, it was able to simply read the
pre-saved outputs. This was an important decision as it kept the
dashboard running smoothly and avoided any issues in loading the data.

The visualisations were built using ``ggplot2'' first before being made
interactive. This was done using ``ggplotly'', which allowed for the
shot maps to have more analytical information attached to them (player
name, xG, minute and outcome). The passing and dribbling heatmaps were
kept as static renderPlot() as they only showed aggregate density
patterns which did not need to be interactive. There were issues with
``ggplotly'' with ``final\_shotmap.rds'', which meant that a change back
to a static plot was needed. They were then processed into Shinylive,
where the dashboard was created. Once this was done, it was able to be
deployed publicly on GitHub Pages.

\subsection{\texorpdfstring{\ul{Metrics
computed}}{Metrics computed}}\label{metrics-computed}

The analysis generated a wide range of metrics across attacking,
progressive and defensive dimensions. All the metrics used directly
contributed to the research question and directly speak to the change in
performance between the two managers. The key metrics that were used
were:

\begin{itemize}
\item
  xG per shot/game by manager - This is one of the most important
  metrics in this analysis as it directly answers whether Ivory Coast
  were creating better quality chances under Faé or Gasset, which was
  the main question being assessed. It captures the quality of the
  chances that have been created rather than whether they were scored.
  This is a more reliable indicator of attacking performance as goals
  scored can be heavily influenced by finishing inconsistencies,
  goalkeeper performances and moments of individual brilliance or
  errors.
\item
  xG Difference per game by manager - This combined the attacking and
  defensive xG for both managers, and allowed us to compare how they
  performed against each other. Rather than estimating xG for and xG
  against only by themselves, the difference between the two condenses
  each managers overall performance into one singular figure. This made
  it useful to analyse the overall performance, seeing whether there was
  an actual improvement.
\item
  Average Shots taken and conceded per game by manager - These were two
  more important metrics that enabled a clear analysis on the
  performances of the managers. Tying this up with the average xG
  generated from these shots allowed for efficient analysis on the
  quality of the chances, and whether or not they were limiting their
  opponents to dangerous or low quality chances.
\item
  Win percentage per manager - This was used to establish an overview of
  the results before introducing the more complex metrics. Without
  knowing what the percentages of each manager were, the analysis would
  have very little context as numbers alone have very little meaning if
  those interpreting can't see how they related to on pitch results.
\item
  Cumulative xG per round - This was used as per game figures do not
  show if there has been a fluctuation per game throughout the
  tournament, and it has the potential to hide anomalies (very high or
  very low xG matches).
\item
  Goals and Assists per player - Used in the key player section as it is
  the most fundamental measure of direct attacking contribution before
  moving into the more complex metrics.
\item
  Deserved winner score: attacking, progressive and defensive components
  - This was used because there are no singular metrics that can decide
  whether a team deserves to win a tournament. A composite score was
  calculated using all three components and a weighting system (decided
  by where they finished), to decide who deserved to win. The stage
  weighting was applied to take into consideration that the teams who
  progressed further into the tournaments are more likely to play
  tougher opponents.
\end{itemize}

\subsection{\texorpdfstring{\ul{Grouping}}{Grouping}}\label{grouping}

All the manager comparison metrics were computed on a game to game basis
rather than a total number. This was because comparing the raw totals
would have been misleading as Faé managed 4 games whereas Gasset managed
3. This would naturally mean that the manager with more games would
accumulate a larger number, so per game rates was the best option for
the analysis as it ensured it was not distorted and was fair.

For the deserved winner score, every per game metric was divided by the
highest value that was recorded across the entire tournament before they
were combined in the three scoring components. This was necessary
because otherwise the scoring may have been distorted by very high
values which may have increased the influence on the final result. Once
this was done, a weighting system was applied depending on where each
team had finished. The teams that went further into the tournament were
given a higher weighting as the further you progress, the tougher the
opponents get.

\subsection{\texorpdfstring{\ul{Dashboard
Design}}{Dashboard Design}}\label{dashboard-design}

The dashboard was built in R Shiny using the `bslib' R package to apply
the themes and the custom background colour. The home page displays the
research question at the top and has the four large navigation buttons
which contain each piece of analysis. The four navigation buttons were
`Tournament Journey', `Before and After Manager Sacking', `Key Players'
and `Was It Deserved?'. Each had its own colour which makes it easier to
distinguish between the sections.

The navigation between each of the panels is handled using
``conditionalPanel()'' blocks which show or hide each of the pages
depending on which has been selected. `ReactiveVal' stores which page is
active, and a Javascript message handler updates it whenever something
has been selected. This means that the pages are able to change smoothly
without having to reload. Each page has it's own back button which
allows for the user to go back to the home screen.

Within each of the pages, the analysis is split into different tabs
using `navset\_pill()' to avoid unrelated information being placed in
the same tabs. This meant that the analysis was in clean locations, and
it would allow the user to find the exact information they need.

Within the dashboard, `renderPlotly()' and 'renderDT() were used so that
the reactive graphs and tables were able to be interactive for the user.
The shot map which compared the team's shots between each of the manager
needed to be interactive so that the analysis would be evident within
the map. For the table, it was made interactive so that the user can
filter between each metric and see how was leading in each stat.

\section{\texorpdfstring{\ul{Findings}}{Findings}}\label{findings}

\subsection{\texorpdfstring{\ul{Tournament Overview and the Group Stage
Struggle}}{Tournament Overview and the Group Stage Struggle}}\label{tournament-overview-and-the-group-stage-struggle}

Across the whole tournament, Ivory Coast played 7 matches, winning 4,
drawing one (won the game via a penalty shootout) and losing twice.
Their two defeats came in the group stage where they lost to Nigeria 1-0
and Equatorial Guinea 4-0 in the final group stage game, which triggered
the managerial change. During the knockout stages, Ivory Coast won three
games and drew one, which they won on penalties. They had performed at a
much higher standard, and that will be analysed later in this section.
Table x summarises Ivory Coast's full tournament timeline, showing who
they had faced, what the score was and what the result of the game was.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.3382}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2647}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1471}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1471}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1029}}@{}}

\caption{\label{tbl-ivory_coast_timeline}Côte d'Ivoire's match by match
results across AFCON}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
competition\_stage.name
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
opponent
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
ivc\_score
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
opp\_score
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
result
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Final & Nigeria & 2 & 1 & Win \\
Semi-finals & Congo DR & 1 & 0 & Win \\
Round of 16 & Senegal & 1 & 1 & Draw \\
Quarter-finals & Mali & 2 & 1 & Win \\
Group Stage & Equatorial Guinea & 0 & 4 & Loss \\
Group Stage & Nigeria & 0 & 1 & Loss \\
Group Stage & Guinea-Bissau & 2 & 0 & Win \\

\end{longtable}

The underlying data from these matches tell us a different story. As
shown in Figure 1, Ivory Coast had a steady accumulation of xG in the
group stage. Across the entire group stage, they accumulated 3.39 xG per
game, which comes to an average of 1.13 per game. Taking the results
into consideration, we can see that they produced inconsistent
performances throughout the group stage, with the two defeats. Despite
losing 4-0 in the last game to Equatorial Guinea, the team had generated
2.06 xG, which is more than the first two games combined. The lack of xG
within those first two games indicate a lack of attacking creativity and
a difficulty in producing high quality opportunities. The majority of
shots that were created accumulated a lower amount of xG, therefore
indicating the likelihood of scoring was low. However in the last game
of the group stage, despite the result, they managed to create the
chances but were not able to finish them off. This sharp defeat led to
the managerial change, even though they narrowly progressed to the next
stage.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/cumulative-xG-chart-1.pdf}}

}

\caption{A graph highliting the cumulative xG of Ivory Coast through
each stage of the tournament}

\end{figure}%

\subsection{\texorpdfstring{\ul{The Managerial Change: The introduction
of Emerse
Faé}}{The Managerial Change: The introduction of Emerse Faé}}\label{the-managerial-change-the-introduction-of-emerse-fauxe9}

The appointment of Emerse Faé was a surprise for many reasons. No one
expected a team to dismiss their manager during the season, especially
as they had reached the knockout stages. However, the performances from
the team under head coach Jean-Louis Gasset caused for immediate change.
The managerial change produced measurable data evidenced changes across
all metrics of Ivory Coast's performance. An examination of six areas of
comparison between the two managers will best highlight the significant
impact that the new manager created.

\subsubsection{\texorpdfstring{\ul{Shot Map and Attacking
Locations}}{Shot Map and Attacking Locations}}\label{shot-map-and-attacking-locations}

The shot maps in Figure 2 offer the clearest immediate illustration of
how the team's attacking intent had changed.

Under Emerse Faé, Ivory Coast's shots appear to be more centrally
concentrated inside and around the penalty area. a large proportion of
these shots came in a dangerous area, which therefore gave them a higher
chance of scoring. This suggests that there was a more direct attacking
structure, which was focused on creating higher quality opportunities in
central areas for their attackers. Additionally, the concentration of
attacks near the goal indicates that they were frequently able to
progress possession in advanced areas, whilst being able to finish the
attacks (scoring or missing the chance).

In contrast, under Jean-Louis Gasset the shot distance is noticeably
wider and more dispersed across the box. There are more attempts from
wider angles, which the StatsBomb xG model assigns that the probability
of those chances to be below 0.1. Goals were rare for the team under
Gasset, and the two goals that they scored came from chances
accumulating 0.075 xg and 0.056 xg respectively.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/manager-comparison-shotmap-1.pdf}}

}

\caption{Comparison Between The Two Managers' Shot Maps}

\end{figure}%

\subsubsection{\texorpdfstring{\ul{Shot Quality vs
Quantity}}{Shot Quality vs Quantity}}\label{shot-quality-vs-quantity}

The shot quality data shown in Table X formalises what the map shows in
data form, illustrating a clear contrast between the two managers. Under
Gasset, Ivory Coast averaged 15.3 shots per game at an average of 0.074
xG per shot. They had a shot on target percentage of 19.6\%, with only 9
of their 46 shots being on target. Even though Jean-Louis Gasset's team
averaged more shots per game, their output was far less effective. Faé's
team scored 6 goals from their 51 shots, whereas Gasset's team ony
scored 2 from 46. These low amount of goals may not seem a lot, however,
tournament football does not always provide high scoring games when
teams of similar level play not to lose rather than win. There is a
clear difference between avg xG per shot, where Fae's team averaged
0.083 per shot compared to Gasset's 0.074. On the surface level the
difference may not seem that large, however over a large amount of shots
it reflects a meaningful improvement in shot quality. This further
supports the shotmap illustrating that the shots under Faé were in more
dangerous areas.

\begin{longtable}[]{@{}lll@{}}
\caption{Shot Quality vs Quantity Comparison by Manager}\tabularnewline
\toprule\noalign{}
Metric & Emerse Faé & Jean-Louis Gasset \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Metric & Emerse Faé & Jean-Louis Gasset \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Matches & 4 & 3 \\
Total Shots & 51 & 46 \\
Shots on Target & 16 & 9 \\
Total xG & 4.22 & 3.39 \\
Goals & 6 & 2 \\
Shots per Game & 12.8 & 15.3 \\
Avg xG per Shot & 0.083 & 0.074 \\
Shot Accuracy (\%) & 31.4 & 19.6 \\
\end{longtable}

The difference in shot on target percentage is huge, as Faé's team has
an average of 31.4\% and Gasset's has an average of 19.6\%. This means
that nearly one third of shots bt Faé's team tested the goalkeeper,
while fewer than one in five did so under Gasset. An interesting
contrast emerges between shot quantity and quality as Gasset's team
attempted more shots but produced a lower shot on target percentage,
lower average xG per shot, fewer goals and a lower total xG. This
suggets that a higher shooting volume did not translate into higher
attacking performance.

Overall, the table suggests that Ivory Coast were a more clinical and
structually efficient attacking side under Faé. Although Gasset's team
had generated more shots in less games, they were lower in xG,
suggesting the shots were taken with more pressure and in positions that
are less likely to test the goalkeeper. In contrast, Fae's team created
higher quality chances, tested the goalkeeper more frequently and
converted their chances more efficiently.

\subsubsection{\texorpdfstring{\ul{Shots Conceded and xG Against and
Defensive
Actions}}{Shots Conceded and xG Against and Defensive Actions}}\label{shots-conceded-and-xg-against-and-defensive-actions}

The data suggests that there was a clear improvement in defensive
perfomance following the managerial change. Under Gasset, Ivory Coast
conceded more shots per game, and xG per shot with 10.3 shots per game
and 1.07 xG per shot. This indicates that they had a vulnerable
defensive structure due to the higher amount of high quality chances
that they conceded.

In contrast, under Faé, there was a slight improvement. Even though they
conceded more xG and more shots, the average for both were lower as
their shots conceded per game was 9 and 0.93 xG per shot. This
illustrates that they restructed their opponents to lower quality
chances, relecting a more organised and resilient structure.

\begin{longtable}[]{@{}lll@{}}
\caption{Ivory Coast Shots Conceded and xG Against Table}\tabularnewline
\toprule\noalign{}
Stat & Jean-Louis Gasset & Emerse Faé \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Stat & Jean-Louis Gasset & Emerse Faé \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
matches & 3 & 4 \\
shots\_conceded & 31 & 36 \\
xg\_conceded & 3.2 & 3.73 \\
shots\_conceded\_per\_game & 10.3 & 9 \\
xg\_conceded\_per\_game & 1.07 & 0.93 \\
\end{longtable}

Furthermore, the defensive metrics used have reinforced the improvement
in their structure. There has been a rise in tackles from 14.3 to 19.5,
suggesting that they have gained more success in tackles and are
defending more as a unit. This can be linked to pressures which has also
increased from 104 to 141.8 per game. This indicates that there has been
a change in intensity, with a more aggressive approach which allows them
to turnover possession high, and start a counter attack using their
quick wingers. Duels per game have also increased from 26.7 to 36.5,
which reflects a more physical approach in contests and ball winning
situations in midfield and defense. Interceptions have increased from
6.3 to 7.8 per game which indicates that there has been an increased
focus on closing down spaces and blocking passing lanes. Finally,
clearances have increased from 11 to 26 per game which suggests that the
defenders are prioritising clearing the ball away from dangerous
situations rather than keep it in the attacking zones.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{readRDS}\NormalTok{(}\StringTok{"defensive\_actions\_manager\_comparison"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lll@{}}
\caption{Defensive Actions between Managers}\tabularnewline
\toprule\noalign{}
Stat & Jean-Louis Gasset & Emerse Faé \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Stat & Jean-Louis Gasset & Emerse Faé \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
matches & 3 & 4 \\
tackles\_pg & 14.3 & 19.5 \\
pressures\_pg & 104 & 141.8 \\
duels\_pg & 26.7 & 36.5 \\
interceptions\_pg & 6.3 & 7.8 \\
clearances\_pg & 11 & 26 \\
\end{longtable}

\subsubsection{\texorpdfstring{\ul{Passing
Structure}}{Passing Structure}}\label{passing-structure}

Figue X shows compares heat maps of passes under each manager.

\begin{verbatim}
Warning: `stat(level)` was deprecated in ggplot2 3.4.0.
i Please use `after_stat(level)` instead.
\end{verbatim}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/passing_heatmap-1.pdf}}

}

\caption{Passing Heatmap Comparison By Managaer}

\end{figure}%

Both heat maps are very similar with very high concentration in deeper
and wider areas. This is further supported by the (PROGRESSIVE PASSING
TABLE) which illustrates the full backs were very influential in
progressive passes. The central concentration is higher under Faé,
suggesting that the midfielders were receiving the ball in more advanced
areas, suggesting a more attacking approach.

\subsubsection{\texorpdfstring{\ul{Dribble
Areas}}{Dribble Areas}}\label{dribble-areas}

Figure X compares Ivory Coast's dribble density under each managers.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/dribble-manager-comparison-plot-1.pdf}}

}

\caption{Dribble Heatmap Comparison By Manager}

\end{figure}%

Under Faé, the dribble areas are heavily concentrated on the wide areas,
with it being spread on both sides of the pitch. It is also very
concentrated centrally just outside the box. This suggests that the
majority of the dribbling was used as a way to break into dangerous
areas, especially targeting the penalty area and isolating the fullbacks
on both wings.

Under Gasset, there are very similar dribbling patterns where the wing
areas gave been targeted. However the major difference is the
overreliance on one side. With Faé, there is high concentration on both
sides, whereas under Gasset, they were only mainly targeting one side of
the pitch.

\subsection{\texorpdfstring{\ul{Key player
contributions}}{Key player contributions}}\label{key-player-contributions}

\subsubsection{\texorpdfstring{\ul{Shot Map}}{Shot Map}}\label{shot-map}

Figure X below illustrates the shot maps of the top five shooters for
Ivory Coast.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/final-shotmap-1.pdf}}

}

\caption{Top 5 Shooters' Heatmap for Ivory Coast}

\end{figure}%

As shown, Sébastian Haller's shots are heavily concentrated very close
to the goals, which highlights his role as the main striker and the main
focal point for all the attacks. In contrast, we can see that the
midfielders, Franck Kessie and Seko Fofana shower a much wider
distribution of shots, as they are attemptimng shots from outside the
box whilst also taking shots within the box. This indicates that they
are making late runs into the box. Krasso also has shots in central
areas as he was used as a backup striker to Haller. Evan Ndicka's
limited amount of shots likely came from set piece situations.

Overall, it appears from the shot~maps that Ivory Coast had a well
organised attacking strategy with distinct player responsibilities. A
focus on effective opportunity generation and attacking via the middle
of the pitch is indicated by the concentration of shots through
dangerous central areas.

\subsubsection{\texorpdfstring{\ul{Goals and
Assists}}{Goals and Assists}}\label{goals-and-assists}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Combined Goals and Assists Table}\tabularnewline
\toprule\noalign{}
player.name & Goals & Assists & GA \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
player.name & Goals & Assists & GA \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Franck Yannick Kessié & 2 & 1 & 3 \\
Sébastien Haller & 2 & 0 & NA \\
Jean-Philippe Krasso & 1 & 0 & NA \\
Oumar Diakité & 1 & 0 & NA \\
Seko Fofana & 1 & 0 & NA \\
Simon Adingra & 1 & 2 & 3 \\
Max-Alain Gradel & 0 & 1 & NA \\
\end{longtable}

From this goals and assists table, we can see that the goals have been
spread the team, as no player has scored more than two goals. Franck
Kessié and Simon Adingra recorded the highest amount of goal
contributions with three each, which highlights their importance in both
chance creation and goal scoring. Overall, the table shows that the team
was very balanced in attack, and they did not have to rely on one
singular player.

\subsubsection{\texorpdfstring{\ul{Dribbling Heat
Maps}}{Dribbling Heat Maps}}\label{dribbling-heat-maps}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/top5_dribblers_heatmap-1.pdf}}

}

\caption{Heatmap of Top 5 dribblers for Ivory Coast}

\end{figure}%

The dribbling heat maps show that Ivory Coast relied heavily on wide
attacking dribbles. Oumar Diakité, Jean-Phillipe Krasso and Simon
Adingra are the three players with the highest concentration in the
wider areas. This further supports the point that they relied on wing
play to attack the opponent and pin them back.

In contrast, we have Seko Fofana who plays in midfield meaning his
dribbling concentration is more central. He used his dribbles to connect
the defense and the attack, and progress the ball through midfield.
Ghislain Konan showed deeper and wider dribbling on the left side of
defense, which illustrated his importance in helping the team relieve
pressure by dribbling out of tough situations.

\subsubsection{\texorpdfstring{\ul{Defensive
stats}}{Defensive stats}}\label{defensive-stats}

The defensive data highlights that Kessié and Seri were the most
efficient defensive midfielders. Kessié recorded a very strong tackle
success rate at 83.3\% whilst Seri recorded 80\%. These were both from a
high number of tackles meaning that they were very effiicient in the
defensive roles that had been set for them. Sangaré also contributed
massively, not only with tackles. All round he was a very solid
defensive midfielder which allowed the attackers freedom to play.

In the wider defensive areas, both Konan and Singo were involved in a
large number of duels and recoveries. Both recorded rather low
percentages for their duels won, however, they both excelled at other
areas such as interceptions and clearances. The low percentage duels won
indicate they were facing difficult one on one situations.

Overall, the table highlights that their defensive strength came from
the effectiveness of their midfield, which was supported by the
aggressive nature of their fullbacks.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.1844}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0567}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0851}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0780}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0709}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0993}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0993}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0709}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0426}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0709}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0638}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 22\tabcolsep) * \real{0.0780}}@{}}
\caption{Ivory Coast Defensive stats by players}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
player.name
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
tackles
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
tackles\_won
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
tackle\_pct
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pressures
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
interceptions
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
inter\_success
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
inter\_pct
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
duels
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
duels\_won
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
duel\_pct
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
clearances
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
player.name
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
tackles
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
tackles\_won
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
tackle\_pct
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
pressures
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
interceptions
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
inter\_success
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
inter\_pct
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
duels
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
duels\_won
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
duel\_pct
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
clearances
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Ghislain Konan & 19 & 8 & 42.1 & 66 & 8 & 5 & 62.5 & 25 & 8 & 32.0 &
15 \\
Franck Yannick Kessié & 12 & 10 & 83.3 & 89 & 4 & 3 & 75.0 & 17 & 10 &
58.8 & 7 \\
Ibrahim Sangaré & 10 & 7 & 70.0 & 96 & 4 & 1 & 25.0 & 13 & 7 & 53.8 &
10 \\
Jean Michaël Seri & 10 & 8 & 80.0 & 51 & 3 & 3 & 100.0 & 11 & 8 & 72.7 &
3 \\
Wilfried Stephane Singo & 9 & 3 & 33.3 & 36 & 7 & 5 & 71.4 & 15 & 3 &
20.0 & 18 \\
Serge Aurier & 8 & 5 & 62.5 & 34 & 6 & 5 & 83.3 & 19 & 5 & 26.3 & 6 \\
Obite Evan Ndicka & 7 & 6 & 85.7 & 48 & 1 & 0 & 0.0 & 13 & 6 & 46.2 &
29 \\
Oumar Diakité & 7 & 6 & 85.7 & 51 & 4 & 2 & 50.0 & 14 & 6 & 42.9 & 2 \\
Willy Boly & 7 & 1 & 14.3 & 28 & 1 & 1 & 100.0 & 9 & 1 & 11.1 & 14 \\
Seko Fofana & 6 & 3 & 50.0 & 63 & 1 & 1 & 100.0 & 8 & 3 & 37.5 & 3 \\
Jean-Philippe Krasso & 5 & 2 & 40.0 & 39 & 1 & 0 & 0.0 & 10 & 2 & 20.0 &
6 \\
Odilon Kossonou & 4 & 2 & 50.0 & 19 & 2 & 2 & 100.0 & 5 & 2 & 40.0 &
10 \\
Simon Adingra & 4 & 2 & 50.0 & 46 & 2 & 1 & 50.0 & 9 & 2 & 22.2 & 0 \\
Christian Kouamé & 2 & 0 & 0.0 & 35 & 0 & 0 & 0.0 & 7 & 0 & 0.0 & 1 \\
Jeremie Boga & 2 & 2 & 100.0 & 12 & 0 & 0 & 0.0 & 5 & 2 & 40.0 & 1 \\
Jonathan Bamba & 2 & 2 & 100.0 & 10 & 0 & 0 & 0.0 & 2 & 2 & 100.0 & 1 \\
Max-Alain Gradel & 2 & 1 & 50.0 & 48 & 1 & 0 & 0.0 & 9 & 1 & 11.1 & 4 \\
Nicolas Pépé & 2 & 1 & 50.0 & 20 & 2 & 2 & 100.0 & 6 & 1 & 16.7 & 0 \\
Jean Thierry Lazare Amani & 1 & 1 & 100.0 & 12 & 1 & 1 & 100.0 & 1 & 1 &
100.0 & 0 \\
Ousmane Diomande & 1 & 1 & 100.0 & 16 & 0 & 0 & 0.0 & 6 & 1 & 16.7 &
4 \\
Sébastien Haller & 1 & 0 & 0.0 & 48 & 2 & 2 & 100.0 & 18 & 0 & 0.0 &
3 \\
Karim Konaté & 0 & 0 & 0.0 & 12 & 0 & 0 & 0.0 & 4 & 0 & 0.0 & 0 \\
\end{longtable}

\subsubsection{\texorpdfstring{\ul{Top 5
Passers}}{Top 5 Passers}}\label{top-5-passers}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{MAINASSIGNMENT_files/figure-pdf/top5-passers-heatmap-1.pdf}}

}

\caption{Heatmap of Passing Areas for Ivory Coast}

\end{figure}%

The passing heat maps indicate that Ivory Coast's buildup play was
heavily concentrated through central areas. Kessié and Fofana
illustrated high passing activity in central areas, which highlights
their importance in connecting the attack and defense with their
progressive passes.

Distribution from the flanks was also important for Ivory Coast with
Singo and Konan both having high concentration in wide areas. The teams
use of fullbacks to support buildup allowed them to maintain width in
attacks. Furthermore, Evan Ndicka had a huge role in progression as the
high concentration suggests he had a key role in starting attacks.

\subsubsection{\texorpdfstring{\ul{Attacking
Stats}}{Attacking Stats}}\label{attacking-stats}

This attacking data table highlights that Seko Fofana is one of the most
influential offensive players. He ranks highly in four out of the 6
metrics, with only progressive passing and box entries being his week
points. Simon Adingra and Oumar Diakaté both played major roles in
attacks, with high amounts of in all metrics apart from progressive
passes which indicates that they are always on the receiving end of
progressive passes.

There is a huge reliance on the fullbacks in buildup with Konan, Aurier
and Singo who have high entries into and touches in the final 3rd, with
a huge amount of progressive passes. This further indicates that there
was a huge reliance on width, and the players involved supported
efficiently.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2301}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1504}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1062}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0796}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1504}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1681}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1150}}@{}}
\caption{Ivory Coast Attacking Metrics}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
player.name
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
carries\_final3rd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
box\_entries
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
dribbles
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
touches\_final3rd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
progressive\_passes
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
shot\_assists
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
player.name
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
carries\_final3rd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
box\_entries
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
dribbles
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
touches\_final3rd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
progressive\_passes
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
shot\_assists
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Ghislain Konan & 12 & 0 & 5 & 163 & 150 & 5 \\
Seko Fofana & 15 & 1 & 9 & 160 & 49 & 5 \\
Oumar Diakité & 7 & 3 & 6 & 146 & 12 & 2 \\
Franck Yannick Kessié & 10 & 1 & 4 & 135 & 75 & 6 \\
Serge Aurier & 6 & 0 & 1 & 133 & 74 & 1 \\
Max-Alain Gradel & 5 & 2 & 2 & 125 & 21 & 5 \\
Simon Adingra & 7 & 3 & 7 & 106 & 15 & 10 \\
Nicolas Pépé & 2 & 4 & 4 & 100 & 9 & 5 \\
Wilfried Stephane Singo & 6 & 1 & 0 & 91 & 89 & 4 \\
Jeremie Boga & 4 & 3 & 4 & 90 & 22 & 4 \\
Jean-Philippe Krasso & 1 & 1 & 8 & 76 & 14 & 4 \\
Ibrahim Sangaré & 1 & 1 & 1 & 74 & 79 & 1 \\
Christian Kouamé & 1 & 1 & 0 & 58 & 8 & 3 \\
Sébastien Haller & 1 & 0 & 0 & 54 & 13 & 1 \\
Jonathan Bamba & 4 & 2 & 1 & 52 & 7 & 1 \\
Jean Michaël Seri & 3 & 0 & 4 & 45 & 51 & 4 \\
Obite Evan Ndicka & 2 & 0 & 0 & 26 & 188 & 2 \\
Karim Konaté & 2 & 2 & 0 & 24 & 5 & 2 \\
Odilon Kossonou & 5 & 0 & 0 & 11 & 55 & 0 \\
Jean Thierry Lazare Amani & 2 & 0 & 0 & 10 & 2 & 1 \\
Ousmane Diomande & 1 & 0 & 0 & 4 & 35 & 0 \\
Willy Boly & 0 & 0 & 0 & 2 & 50 & 0 \\
Idrissa Doumbia & 0 & 0 & 0 & 0 & 1 & 0 \\
Yahia Fofana & 0 & 0 & 0 & 0 & 137 & 0 \\
\end{longtable}

\subsection{\texorpdfstring{\ul{Was the title
deserved?}}{Was the title deserved?}}\label{was-the-title-deserved}

A metric was created to determine who deserved to win the tournament. A
weighting was applied depending on what stage the team reached, with the
final having a weight of 1, semi final 0.9, Quarter Final 0.85, Round of
16 0.8 and the Group Stage 0.75. This was done so that all factors could
be taken into consideration, such as the amount of games they had to
play and teams playing harder opponents later in the tournament.
Attacking, progressive and defensive stats were also included in the
metric.

\begin{verbatim}
# A tibble: 24 x 21
   team.name          competition_stage.name    stage_weight matches goals xg_pg
   <chr>              <fct>                            <dbl>   <int> <int> <dbl>
 1 Côte d'Ivoire      Final                             1          7     8  1.09
 2 Egypt              Round of 16                       0.8        4     7  1.57
 3 Nigeria            Final                             1          7     7  1.39
 4 Cape Verde Islands Quarter-finals                    0.85       5     8  1.36
 5 South Africa       Semi-final → 3rd Place F~         0.9        7     7  1.07
 6 Angola             Quarter-finals                    0.85       5     9  1.33
 7 Senegal            Round of 16                       0.8        4     9  1.3 
 8 Congo DR           Semi-final → 3rd Place F~         0.9        7     6  1.63
 9 Mali               Quarter-finals                    0.85       5     5  1.17
10 Mauritania         Round of 16                       0.8        4     3  0.93
# i 14 more rows
# i 15 more variables: shots_on_target_pg <dbl>, shot_assists_pg <dbl>,
#   progressive_passes_pg <dbl>, dribbles_pg <dbl>, carries_final3rd_pg <dbl>,
#   box_entries_pg <dbl>, touches_final3rd_pg <dbl>, tackles_won_pg <dbl>,
#   interceptions_pg <dbl>, clearances_pg <dbl>, pressures_pg <dbl>,
#   attack_score <dbl>, progressive_score <dbl>, defensive_score <dbl>,
#   overall_score <dbl>
\end{verbatim}

The scores revealed that Ivory Coast did infact deserve to win the
tournament despite their poor Group Stage performance as their
underlying metrics improved significantly across the tournament. Their
transition from the inconsistent group of performers to a more efficient
team in the knockout stages is reflected in the high attacking score.
All round, they are the most consistent team across the four key
attributes.

Nigeria who also got to the final are in third place, suggesting that
Ivory Coast's win in the final was deserved. While Nigeria were more
consistent throughout the tournament, Ivory Coast's effective knockout
stage, tied with the weighting of reaching the final, allowed for them
to finish at the top of this chart.

Interestingly, Egypt ranked second in this chart despite finishing in
the Round of 16. There are many factors to this as they were very strong
in the group stages, however, key player Mohammed Salah suffered an
injury meaning they were missing their strongest player for the knockout
stages.

\section{\texorpdfstring{\ul{Discussion, Limitation and
Conclusion}}{Discussion, Limitation and Conclusion}}\label{discussion-limitation-and-conclusion}

\subsection{\texorpdfstring{\ul{Implication of the
Findings}}{Implication of the Findings}}\label{implication-of-the-findings}

The findings reveal that the managerial change from Gasset to Faé had a
measurable impact on Ivory Coast's underlying performance metrics rather
than just the results. There was an improvement in their shot quality as
their xG per shot had risen from 0.074 to 0.083. Even though it is a
small increase, over an increase number of shots, the margin becomes
bigger and bigger. This combined with the increase shot on target
percentage rose from 19.6\% to 31.4\%, suggesting that the team were not
only creating better opportunities, they were also testing the
goalkeeper a lot more. The defensive data also illustrates the
improvement as the increase suggests that there was a structural change
which solidified their team. The improvement in attacking and defensive
metrics were key to them winning the tournament, and the managerial
change helped manage that.

The findings from this analysis have different implications for
different audiences.

Firstly for coaches and sporting directors, the data demonstrates that a
change of manager during a tournament can produce improvements on the
pitch and in underlying performances metrics. The improvement seen under
Faé practically won Ivory Coast the tournament as they were on the brink
of elimination under Gasset. these improvements were visible with teh
results and multiple metrics, such as the shot locations became more
central which led to an improvement in their shot quality. The dribbling
and passing structures had shifted into more advanced areas of the pitch
will indicates that they were had a more attacking structure and were
creating more dangerous attacks. This on the field improvement could
impact future decisions about whether making a managerial change during
a competition will benefit or hinder the team involved.

For analysts, the dashboard provides offers a way of looking at ivory
Coast's tournament performance beyond just their results and basic
stats. The manager comparison section shows how event level data can be
used to build a more compete analysis of how a team has performed. The
data shows that Ivory Coast had an improvement after the managerial
change, which in the end enabled them to win the competition. The shot
metrics, defensive actions tables and the spatial heatmaps provide the
analysts a level of detail which results based analysis cannot offer.
This would allow analysts to pinpoint exactly where they have improved
and what they can improve on. This kind of approach could easily be
applied to other teams or competitions where the event level data is
available for use. Whether it is assessing the impact of a tactical
change during the season, analysing if a strong run of results is
genuinely supported by the underlying performance data, or identifying
which players are most important to a team's overall structure and style
of play, the same methodology used in this project could easily be
adapted to explore those questions in a similarly effective way.

\subsection{\texorpdfstring{\ul{Limitations}}{Limitations}}\label{limitations}

One limitation of this analysis is that the StatsBomb data does not
include tracking data for off the ball movement. This would be
particularly relevant for the defensive analysis when comparing the two
managers as these metrics such as pressing intensity and defensive line
height cannot be measured from event level data alone. The improvement
between the two managers can only be calculated through on-ball actions
like tackles, pressures, interceptions and clearances rather than a
direct observation of how the defense as a whole were structured.

Another limitation of the analysis is the deserved winner table. Even
though the deserved winner score placed Ivory Coast at the tournament
rankings, the weightings assigned and the metrics used were all
judgement calls that others may use differently. The choices that have
been made are reasonable and bode well with the data that was available,
however, if other data became available, then the metrics and the
weighting could be rebuilt. In regard to the weighting, it was based on
how far a team reached in the tournament, due to the opposition being
more difficult later. Being able to compute the difficulty of each
opponent and using that average as the weighting could be something used
with different data.

\subsection{\texorpdfstring{\ul{Future
Outlook}}{Future Outlook}}\label{future-outlook}

There are several ways this analysis could be improved for future
outlook. Firstly, with the access to additional data, StatsBomb's freeze
frame data which records the positions of all the 22 players at the
moment of each event would have allowed for a much more precise analysis
(POTENTIAL REFERENCE). This would have enabled an analysis of the
defensive shape and the quality of the shots in relation to where the
defenders are positioned. This gives a clear picture of how dangerous
the chance is, as shots where the attacker is surrounded by no one and
one where they are under pressure are completely different. This is
something that normal xG models cannot capture.

\subsection{\texorpdfstring{\ul{Conclusion}}{Conclusion}}\label{conclusion}

\section{References}\label{references}




\end{document}
